preprocessing_level: 8
median_filter_size: 10
hole_area_threshold: 1000
min_tissue_fraction: 0.1
num_workers: 1

extractor_models:
  plip:
    extraction_levels: [1, 3, 5]       # extract at 20x, 5x, and 1.5x
    patch_dimensions: [256, 256]    # extract 256x256 patches
  imagenet:
    extraction_levels: [1, 3, 5]       # extract at 20x, 5x, and 1.5x
    patch_dimensions: [256, 256]    # extract 256x256 patches
  region_hipt:
    extraction_levels: [1]          # extract only at 20x, as HIPT is pretrained at this level
    patch_dimensions: [4096, 4096]  # extract 4096x4096 patches
