# data paths
output_dir:

# feature extractor
extraction_level: 1
extractor_model: resnet50_imagenet

# task
target: primary
n_classes: 2
n_folds: 5

# classifier
classifier: TransformerClassifier
final_activation: softmax
dropout: 0.25

# naive pooling classifier specific parameters
pooling_function: max

# attention classifier specific parameters
attention_dim: 128

# transformer classifier specific parameters
n_heads: 2
activation_function: 'relu'
n_layers: 2

# training parameters
learning_rate: 2e-4
weight_decay: 1e-5
patience: 10
num_workers: 0
seed: 0 
max_epochs: 100
patience: 10
accumulate_grad_batches: 32


# heatmaps
generate_heatmap_vectors: False
level_for_visualizing_heatmap: 7
dpi: 80
patch_size_during_feature_extraction: 4096
level_during_feature_extraction: 1

mode: eval