# data paths
manifest_file_path:             # path to the manifest file
output_dir:                     # path to the output directory, where all pipeline output will be stored


# settings for /source/end_to_end/2_preprocess.py
preprocessing_level: 8          # level at which the foreground is automatically segmented
median_filter_size: 10          # size of the median filter used to smooth the foreground mask
hole_area_threshold: 1000       # size of the holes in the foreground mask to be filled
min_tissue_fraction: 0.1        # minimum fraction of tissue in a patch for it to be included
num_workers:                    # number of workers for parallel processing during tessalation

patch_dimensions_options: [     # patch sizes that will be extracted
  [256,256],                    # 256x256 is for imagenet and plip
  [4096,4096]                   # 4096x4096 is for HIPT
]

patch_dimension_256_options:    # settings only for 256x256 patches
  extraction_levels: [1, 3, 5]   # extract at 20x, 5x, and 1.5x

patch_dimension_4096_options:   # settings only for 4096x4096 patches
  extraction_levels: [1]         # extract only at 20x, as HIPT is pretrained at this level

