# data paths
dataset_dir:
slide_paths_txt_file: 

# preprocessing
preprocessing_level: 8
extraction_level: 1
median_filter_size: 10
hole_area_threshold: 1000
min_tissue_fraction: 0.1
patch_dimensions: [4096, 4096]
num_workers: 