# data paths
dataset_dir:
slide_paths_txt_file:

# extraction
extraction_level: 1
patch_dimensions: [4096, 4096]
extraction_batch_size: 1
extractor_model: region_hipt
num_workers:

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth

