dataset_dir: /hpc/dla_patho/premium/rens/pathology_classification/data/full_slide_comparison
slide_paths_txt_file: /hpc/dla_patho/premium/rens/pathology_classification/data/full_slide_comparison/slide_list.txt

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /hpc/dla_patho/premium/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /hpc/dla_patho/premium/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth

num_workers: 8