output_dir: /home/rens/repos/pathology_classification/data/example_dataset
slide_paths_txt_file: /home/rens/repos/pathology_classification/data/example_dataset/slide_list.txt

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth