# data paths
dataset_dir: /hpc/dla_patho/premium/rens/pathology_classification/data/premium
features_dir: 
slides_dir: /hpc/dla_patho/premium/pathology/slides
segmentations_dir:
patch_coordinates_dir: 
output_dir: 

# preprocessing
patch_dimensions: [4096, 4096]

# extraction
extraction_batch_size: 1
extractor_model: region_hipt

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /hpc/dla_patho/premium/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /hpc/dla_patho/premium/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth