# data paths
dataset_dir: /mnt/hpc/rens/pathology_classification/data/premium 
slide_paths_txt_file: /mnt/hpc/rens/pathology_classification/data/premium/slide_list.txt


# preprocessing
patch_dimensions: [4096, 4096]

# extraction
extraction_batch_size: 1
extractor_model: region_hipt

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth