# data paths
dataset_dir: /mnt/hpc/rens/camelyon/CAMELYON16/output
cross_val_splits_dir: 
features_dir: 
slides_dir: /mnt/hpc/rens/camelyon/CAMELYON16/images
segmentations_dir:
patch_coordinates_dir: 
output_dir: 

# preprocessing
preprocessing_level: 8
extraction_level: 1
median_filter_size: 10
hole_area_threshold: 1000
min_tissue_fraction: 0.01
patch_dimensions: [4096, 4096]

# extraction
extraction_batch_size: 1
extractor_model: region_hipt

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /mnt/hpc/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth

###