# data paths
dataset_dir: /hpc/dla_patho/premium/rens/pathology_classification/data/premium
slide_paths_txt_file: /hpc/dla_patho/premium/rens/pathology_classification/data/premium/slide_list.txt


# preprocessing
preprocessing_num_workers: 18
patch_dimensions: [256, 256]

# extraction
extraction_batch_size: 128
extractor_model: resnet50_imagenet

# HIPT checkpoints
patch_level_hipt_checkpoint_path: /hpc/dla_patho/premium/rens/pathology_classification/checkpoints/vit256_small_dino.pth
region_level_hipt_checkpoint_path: /hpc/dla_patho/premium/rens/pathology_classification/checkpoints/vit4k_xs_dino.pth

# classify
num_workers: 0
n_features: 1024