target: label
n_features: 192
n_classes: 3
pooling+function: max
final_activation: softmax
manifest_dir: "/mnt/hpc/rens/hipt/data/fold_dir_dcb/fold_0"
features_dir: "/mnt/hpc/pathology/hipt_features2/hipt/8d74jc21/features/global/slide"
num_workers: 1
